"""create initial tables

Revision ID: dc04d0caf4b9
Revises: 
Create Date: 2026-04-23 15:32:20.610930

"""
from typing import Sequence, Union
import pgvector.sqlalchemy


from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dc04d0caf4b9'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accounts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('account_type', sa.Enum('ASSET', 'LIABILITY', 'EQUITY', 'REVENUE', 'EXPENSE', name='accounttype'), nullable=False),
    sa.Column('normal_balance', sa.Enum('DEBIT', 'CREDIT', name='normalbalance'), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('current_balance', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_accounts_name'), 'accounts', ['name'], unique=True)
    op.create_table('financial_insights',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('insight_text', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('memory_patterns',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('description_pattern', sa.Text(), nullable=False),
    sa.Column('debit_account_name', sa.String(), nullable=False),
    sa.Column('credit_account_name', sa.String(), nullable=False),
    sa.Column('frequency', sa.String(), nullable=True),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1536), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_memory_patterns_description_pattern'), 'memory_patterns', ['description_pattern'], unique=False)
    op.create_table('policy_memory',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('policy_name', sa.String(), nullable=False),
    sa.Column('policy_value', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('policy_name')
    )
    op.create_table('transactions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transactions_date'), 'transactions', ['date'], unique=False)
    op.create_table('transaction_lines',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('transaction_id', sa.UUID(), nullable=False),
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.Column('debit', sa.Float(), nullable=False),
    sa.Column('credit', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transaction_lines')
    op.drop_index(op.f('ix_transactions_date'), table_name='transactions')
    op.drop_table('transactions')
    op.drop_table('policy_memory')
    op.drop_index(op.f('ix_memory_patterns_description_pattern'), table_name='memory_patterns')
    op.drop_table('memory_patterns')
    op.drop_table('financial_insights')
    op.drop_index(op.f('ix_accounts_name'), table_name='accounts')
    op.drop_table('accounts')
    # ### end Alembic commands ###
